prima_app/urls.py
from django.urls import path
from .views import homepage, menu, chisiamo, variabili, index
app_name = 'prima_app'

urlpatterns = [
    path('welcome/', homepage, name='home'),
    path('menu/', menu, name='menu'),
    path('chisiamo/', chisiamo, name='chisiamo'),
    path('variabili/', variabili, name='variabili'),
    path('index/', index, name='index'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from prima_app.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name='index'),
    path('prima_app/', include('prima_app.urls')),
    path('seconda_app/', include('seconda_app.urls')),
]

seconda_app/urls.py
from django.urls import path
from .views import esempio_if,esempio_ifelse, esempio_elif, esempio_for
app_name = 'seconda_app'
urlpatterns = [
    path('if', esempio_if, name='if'),
    path('ifelse', esempio_ifelse, name='ifelse'),
    path('ifelif', esempio_elif, name='elif'),
    path('for', esempio_for, name='for'),
]

libreria/models.py
from django.db import models

# Create your models here.
class Genere_SR(models.Model):
    contenuto = models.CharField()

    def __str__(self):
        return self.contenuto
    
    class Meta:
        verbose_name = "Genere"
        verbose_name_plural = "Generi"

class Autore_SR(models.Model):
    nome = models.CharField()
    cognome = models.CharField()

    def __str__(self):
            return self.nome + " "+ self.cognome
    
    class Meta:
        verbose_name = "Autore"
        verbose_name_plural = "Autori"

class Libro_SR(models.Model):
    titolo = models.CharField()
    isbn = models.CharField(max_length=18)
    pubblicazione = models.ManyToManyField(Genere_SR)
    autore = models.ForeignKey(Autore_SR, on_delete=models.CASCADE, related_name='libri')

    def __str__(self):
        return self.titolo

    class Meta:
        verbose_name = "Libro"
        verbose_name_plural = "Libri"

news/models.py
from django.db import models

# Create your models here.
class Giornalista(models.Model):

<<<<<<< HEAD
nome = models.CharField(max_length=28)
cognome = models.CharField(max_length=28)

def __str__(self):
    return self.nome + " "+ self.cognome

class Articolo(models.Model):

titolo = models.CharField(max_length=100)
contenuto = models.CharField()
giornalista = models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")

def __str__(self):
    return self.titolo
=======
    nome = models.CharField(max_length=28)
    cognome = models.CharField(max_length=28)

    def __str__(self):
        return self.nome + " "+ self.cognome

class Articolo(models.Model):

    titolo = models.CharField(max_length=100)
    contenuto = models.CharField()
    giornalista = models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")

    def __str__(self):
        return self.titolo
>>>>>>> L22

prima_app/models.py
from django.db import models

# Create your models here.

seconda_app/models.py
from django.db import models

# Create your models here.

libreria/views.py
from django.shortcuts import render

# Create your views here.

prima_app/views.py
from django.http import HttpResponse 
from django.shortcuts import render
# Create your views here.

def homepage(request):
    return HttpResponse("<h1>Ciao a tutti! Benvenuti nella homepage!</h1>")

def menu(request):
    return HttpResponse("<ol><li>Prima opzione</li><li>Seconda opzione</li><li>Terza opzione</li></ol>")

def chisiamo(request):
    return render(request, "chi_siamo.html")

def variabili(request):
    context= { 'var1': '10','var2': 'ciao', 'var3' : '123 hello world'}
    return render(request, "variabili.html",context)

def index(request):
    return render(request, "index.html")

seconda_app/views.py
from django.shortcuts import render
import datetime
# Create your views here.
#L6
def esempio_if(request):
    #https://www.decodejava.com/django-template-if-tag.htm
    #Creating a dictionary of key-value pairs
    dic = { 'var1' : 200,
    'var2' : 200,
    'var3' : 300 }
    #Calling the render() method to render the request from es_if.html page by using the dictionary, dic
    return render(request, "es_if.html", dic)

#L7
def esempio_ifelse(request):
    #https://www.decodejava.com/django-template-if-else-tag.htm
    dic = { 'var1' : 'admin',
    'var2' : 'admin',
    'var3' : 600 }
    return render(request, "es_ifelse.html", dic)

#L8
def esempio_elif(request):
    dic = { 'var1' : 100,
    'var2' : 100.0,
    'var3' : 100.50,
    'str1' : 'Hello',
    'str2' : 'hello',
    'str3' : "Hello",
    'list1': [1, datetime.date(2019,7,16), 'Make your life productive!'],
    'list2': [2, datetime.date(2019,7,16), 'Do not give up!']}
    return render(request, "es_ifelif.html", dic)

#L9
def esempio_for(request):
    #https://www.decodejava.com/django-template-for-tag.htm
    dic = { 'list1': [1, datetime.date(2019,7,16), 'Do not give up!'],'list2': [1, datetime.date(2019,7,16), 'Do not give up!'] }
    return render(request, "es_for.html", dic)

prima_app/templates/chi_siamo.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Chi siamo
{%endblock title%}

{%block content%}
    <h3>Siamo quelli che siamo ?</h3>
{%endblock content%}

prima_app/templates/index.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Index
{%endblock title%}

{%block content%}
    <ol><li><a href="{% url 'index'%}">index</a></li>
        <li><a href="{% url 'home'%}">home page welcome</a></li>
        <li><a href="{% url 'menu'%}">menu</a></li>
        <li><a href="{% url 'chisiamo'%}">chi siamo</a></li>
        <li><a href="{% url 'variabili'%}">variabili</a></li>
    </ol>
{%endblock content%}

prima_app/templates/variabili.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Index
{%endblock title%}

{%block content%}
   <ol>
    <li> {{ var1 }}</li>
    <li> {{ var2 }}</li>
    <li> {{ var3 }}</li>
</ol>
{%endblock content%}

seconda_app/templates/es_for.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | For
{%endblock title%}

{%block content%}
   Looping over a sequence of items using <b>forloop.counter</b> variable:
	<br/>
	{% for x in list2 %}
		<i>{{ forloop.counter }} </i> : {{ x }}<br>
	{% endfor %}
	<br/>


	Looping over a sequence of items using <b>forloop.counter0</b> variable:
	<br/>
	{% for x in list2 %}
		<i>{{ forloop.counter0 }}</i> : {{ x }}<br/>
	{% endfor %}
	<br/>


	Printing the first element of sequence using <b>forloop.first</b> variable:
	<br/>
	{% for x in list2 %}
		{% if forloop.first %}
			<i>The first item</i> - {{ x }}
		{% endif%}
	{% endfor %}
	<br/>
	<br/>


	Printing the last element of sequence using <b>forloop.last</b> variable:
	<br/>
	{% for x in list2 %}
		{% if forloop.last %}
			<i>The last item</i> - {{ x }}
		{% endif%}
	{% endfor %}
	<br/>
	<br/>


	Printing the left over items in the sequence using <b>forloop.revcounter</b> variable:
	<br/>
	{% for x in list2 %}
		<i>Total number of leftover item to be iterated</i> - {{ forloop.revcounter }}<br/>
		<i>Item</i> - {{ x }}<br/>
	{% endfor %}
	<br/>


	Printing the left over items in the sequence using <b>forloop.revcounter0</b> variable:
	<br/>
	{% for x in list2 %}
		<i>Total number of leftover item to be iterated</i> - {{ forloop.revcounter0 }}<br/>
		<i>Item</i> - {{ x }}<br/>
	{% endfor %}
	<br/>


	Printing the reversed sequence of items using <b>reversed</b> attribute of <b>for</b> tag: <br/>
	{% for x in list2 reversed %}
		<i>Item</i> - {{ x }}<br/>
	{% endfor %}
{%endblock content%}

seconda_app/templates/es_if.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | IF
{%endblock title%}

{%block content%}
   <b>var1 = {{ var1 }}</b> <br/>
	<b>var2 = {{ var2 }}</b> <br/>
	<b>var3 = {{ var3 }}</b> <br/>


	{% if var1 < var2 %}
		<p><i>var1 is smaller than var2 </i></p>
	{% endif %}


	{% if var1 > var2 %}
		<p><i>var1 is greater than var2 </i></p>
	{% endif %}


	{% if var1 <= var2 %}
		<p><i>var1 is less than or equal to var2 </i></p>
	{% endif %}


	{% if var1 >= var2 %}
		<p><i>var1 is greater than or equal to var2 </i></p>
	{% endif %}


	{% if var1 == var2 %}
		<p><i>var1 is equal to var2 </i></p>
	{% endif %}


	{% if var1 != var2 %}
		<p><i>var1 is not equal to var2 </i></p>
	{% endif %}


	{% if var1 < var2 and var1 < var3 %}
		<p><i>var1 is less than var2 and var1 is less than var3 </i></p>
	{% endif %}


	{% if var1 < var2 or var3 < var2 %}
		<p><i>var1 is less than var2 or var3 is less than var2 </i></p>
	{% endif %}


	{% if not var1 > var2 %}
		<p><i>var1 is not greater than var2 </i></p>
	{% endif %}
{%endblock content%}

seconda_app/templates/es_ifelse.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | IF ELSE
{%endblock title%}

{%block content%}
   <b>var1 = {{ var1 }}</b> <br/>
	<b>var2 = {{ var2 }}</b> <br/>
	<b>var3 = {{ var3 }}</b> <br/>


	{% if var1 < var2 %}
		<p><i>var1 is smaller than var2 </i></p>
	{% else %}
		<p><i>var1 is not smaller than var2 </i></p>
	{% endif %}


	{% if var1 > var2 %}
		<p><i>var1 is greater than var2 </i></p>
	{% else %}
		<p><i>var1 is not greater than var2 </i></p>
	{% endif %}


	{% if var1 <= var2 %}
		<p><i>var1 is less than or equal to var2 </i></p>
	{% else %}
		<p><i>var1 is not less than or not equal to var2 </i></p>
	{% endif %}


	{% if var1 >= var2 %}
		<p><i>var1 is greater than or equal to var2 </i></p>
	{% else %}
		<p><i>var1 is not greater than or not equal to var2 </i></p>
	{% endif %}


	{% if var1 == var2 %}
		<p><i>var1 is equal to var2 </i></p>
	{% else %}
		<p><i>var1 is not equal to var2 </i></p>
	{% endif %}


	{% if var1 != var2 %}
		<p><i>var1 is not equal to var2 </i></p>
	{% else %}
		<p><i>var1 is equal to var2 </i></p>
	{% endif %}


	{% if var1 < var2 and var1 < var3 %}
		<p><i>var1 is less than var2 and var1 is less than var3 </i></p>
	{% else %}
		<p><i>var1 is not less than var2 and var1 is not less than var3 </i></p>
	{% endif %}


	{% if var1 < var2 or var3 < var2 %}
		<p><i>var1 is less than var2 or var3 is less than var2 </i></p>
	{% else %}
		<p><i>var1 is not less than var2 or var3 is not less than var2 </i></p>
	{% endif %}


	{% if not var1 > var2 %}
		<p><i>var1 is not greater than var2 </i></p>
	{% else %}
		<p><i>var1 is greater than var2 </i></p>
	{% endif %}


	{% if a != a %}
		 <i>a is not equal to a </i></b>
	{% else %}
		 <i>a is equal to a </i></b>
	{% endif %}


	{% if 'hi' != 'hi' %}
		 <i>hi is not equal to hi </i></b>
	{% else %}
		 <i>hi is equal to hi </i></b>
	{% endif %}


	{% if 'hello world' != "hello world" %}
		 <i>hello world is not equal to hello world </i></b>
	{% else %}
		 <i>hello world is equal to hello world </i></b>
	{% endif %}


	{% if zero == 0 %}
		 <i>zero is equal to 0 </i></b>
	{% else %}
		 <i>zero is not equal to 0</i></b>
	{% endif %}
{%endblock content%}

seconda_app/templates/esifelif.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | if elif
{%endblock title%}

{%block content%}
   <b>var1 = {{ var1 }}</b> <br/>
<b>var2 = {{ var2 }}</b> <br/>
<b>var3 = {{ var3 }}</b> <br/>
<b>str1 = {{ str1 }}</b> <br/>
<b>str2 = {{ str2 }}</b> <br/>
<b>str3 = {{ str3 }}</b> <br/>
<b>list1 = {{ list1 }}</b> <br/>
<b>list2 = {{ list2 }}</b> <br/>


{% if var1 < var2 %}
	<p><i>var1 is smaller than var2 </i></p>
{% elif var1 > var2 %}
	<p><i>var1 is greater than var2 </i></p>
{% endif %}


{% if var1 > var2 %}
	<p><i>var1 is greater than var2 </i></p>
{% elif var1 < var2 %}
	<p><i>var1 is less than var2 </i></p>
{% endif %}


{% if var1 <= var2 %}
	<p><i>var1 is less than or equal to var2 </i></p>
{% elif var1 > var2 %}
	<p><i>var1 is greater than var2 </i></p>
{% endif %}


{% if var1 >= var2 %}
	<p><i>var1 is greater than or equal to var2 </i></p>
{% elif var < var1 %}
	<p><i>var1 is less than var2 </i></p>
{% endif %}


{% if var1 == var2 %}
	<p><i>var1 is equal to var2 </i></p>
{% elif var != var2 %}
	<p><i>var1 is not equal to var2 </i></p>
{% endif %}


{% if var1 != var2 %}
	<p><i>var1 is not equal to var2 </i></p>
{% elif var1 == var2 %}
	<p><i>var1 is equal to var2 </i></p>
{% endif %}


{% if var1 < var2 and var1 < var3 %}
	<p><i>var1 is less than var2 and var1 is less than var3 </i></p>
{% elif var1 > var2 and var1 > var3%}
	<p><i>var1 is greater than var2 and var1 is greater than var3 </i></p>
{% endif %}


{% if var1 < var2 or var3 < var2 %}
	<p><i>var1 is less than var2 or var3 is less than var2 </i></p>
{% elif var1 > var2 or var3 > var2 %}
	<p><i>var1 is greater than var2 or var3 is greater than var2 </i></p>
{% endif %}


{% if not var1 > var2 %}
	<p><i>var1 is not greater than var2 </i></p>
{% elif not var1 < var2 %}
	<p><i>var1 is not less than var2 </i></p>
{% endif %}



{% if str1 == str3 %}
	<p><i>str1 is equal to str3</i></p>
{% elif str1 != str3 %}
	<p><i>str1 is not equal to str3</i></p>
{% endif %}


{% if str1 == str2 %}
	<p><i>str1 is equal to str2</i></p>
{% elif str1 != str2 %}
	<p><i>str1 is not equal to str2</i></p>
{% endif %}



{% if list1 == list2 %}
	<p>list1 is equal to list2</p>
{% elif list1 != list2 %}
	<p><i>list1 is not equal to list2</i></p>
{% endif %}


{% if a != a %}
	<p><i>a is not equal to a </i></p>
{% elif a == a %}
	<p><i>a is equal to a </i></p>
{% endif %}


{% if 'hi' != 'hi' %}
	<p><i>hi is not equal to hi </i></p>
{% elif 'hi' == 'hi' %}
	<p><i>hi is equal to hi </i></p>
{% endif %}


{% if 'hello world' != "hello world" %}
	<p><i>hello world is not equal to hello world </i></p>
{% elif 'hello world' == "hello world" %}
	<p><i>hello world is equal to hello world </i></p>
{% endif %}


{% if zero == 0 %}
	<p><i>zero is equal to 0 </i></p>
{% elif zero != 0 %}
	<p><i>zero is not equal to 0</i></p>
{% endif %}
{%endblock content%}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Web apps{% endblock title %}</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">Primo Progetto</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/"> <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Prima
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'prima_app:index' %}">Index</a>
                    <a class="dropdown-item" href="{% url 'prima_app:home' %}">Home</a>
                    <a class="dropdown-item" href="{% url 'prima_app:chisiamo' %}">Chi siamo</a>
                    <a class="dropdown-item" href="{% url 'prima_app:variabili' %}">Variabili</a>

                </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Seconda
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'seconda_app:if' %}">if</a>
              <a class="dropdown-item" href="{% url 'seconda_app:ifelse' %}">ifelse</a>
              <a class="dropdown-item" href="{% url 'seconda_app:elif' %}">elif</a>
              <a class="dropdown-item" href="{% url 'seconda_app:for' %}">for</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Blog
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <!--  <a class="dropdown-item" href="/blog/crea-post">Crea post</a> -->
              <a class="dropdown-item" href="{% url 'blog:crea_post' %}">Crea post</a>
              <a class="dropdown-item" href="{% url 'blog:lista_post' %}">Leggi post</a>

            </div>
          </li>

        </ul>

      </div>
    </nav>

    <div class="container my-4">
      <h3></h3>
     {%block content%}

     {%endblock content%}
    </div>

   </body>
</html>